ci: Temporarily disable hexagon-unknown-none-elf build
https://github.com/rust-lang/compiler-builtins/pull/577 caused regression on no-std hexagon:

```
  error: symbol 'fma' is already defined

  error: symbol 'fmax' is already defined
```