ci: gba crate is broken due to recent nightly bug
https://github.com/rust-lang/rust/pull/127853#issuecomment-2257323333

```
  error[E0736]: attribute incompatible with `#[naked]`
     --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gba-0.11.6/src/asm_runtime.rs:164:1
      |
  164 | /// Returns 0 in `r0`, while placing the `numerator` into `r1`.
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the `` attribute is incompatible with `#[naked]`
  ...
  172 | #[naked]
      | -------- function marked with `#[naked]` here
```