ci: Temporarily pin powerpc linux test to nightly-2025-02-25
```
  qemu: uncaught target signal 4 (Illegal instruction) - core dumped
  error: test failed, to rerun pass `--test arc`

  Caused by:
    process didn't exit successfully: `qemu-ppc /home/runner/work/portable-atomic/portable-atomic/target/powerpc-unknown-linux-gnu/debug/deps/arc-ad00c152bf10ad61` (signal: 4, SIGILL: illegal instruction)
  test alloc_tests::manually_share_arc ... ::endgroup::
  error: process didn't exit successfully: `/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo test -Z doctest-xcompile -v --target powerpc-unknown-linux-gnu --manifest-path portable-atomic-util/Cargo.toml --features std` (exit status: 101)
```