Temporarily disable aarch64_be test due to core_simd bug
https://github.com/rust-lang/portable-simd/pull/348

```
error[E0432]: unresolved imports `core::arch::aarch64::vqtbl1q_u8`, `core::arch::aarch64::vtbl1_u8`
   --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../portable-simd/crates/core_simd/src/swizzle_dyn.rs:20:46
    |
 20 |         use core::arch::aarch64::{uint8x8_t, vqtbl1q_u8, vtbl1_u8};
    |                                              ^^^^^^^^^^  ^^^^^^^^ no `vtbl1_u8` in `core_arch::arch::aarch64`
    |                                              |
    |                                              no `vqtbl1q_u8` in `core_arch::arch::aarch64`
    |
 help: a similar name exists in the module
    |
 20 |         use core::arch::aarch64::{uint8x8_t, vst1q_u8, vtbl1_u8};
    |                                              ~~~~~~~~
 help: a similar name exists in the module
    |
 20 |         use core::arch::aarch64::{uint8x8_t, vqtbl1q_u8, vtrn1_u8};
    |                                                          ~~~~~~~~
```