ci: Temporarily disable asan and msan with fat LTO
```
  AddressSanitizer:DEADLYSIGNAL
  =================================================================
  ==9490==ERROR: AddressSanitizer: SEGV on unknown address 0x01fef692f240 (pc 0x55cf0d4e0fd7 bp 0x7ffd03fc2bf0 sp 0x7ffd03fc2b40 T0)
  ==9490==The signal is caused by a READ memory access.
      #0 0x55cf0d4e0fd7  (/home/runner/work/portable-atomic/portable-atomic/target/fat-lto/x86_64-unknown-linux-gnu/release/deps/portable_atomic_util-00d6667bc63e2ad8+0x186fd7) (BuildId: c0b91b02598535e2c737f09aa3b674d9ad0b0dad)
      #1 0x7f99a6e2a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
      #2 0x7f99a6e2a28a  (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
      #3 0x55cf0d42c024  (/home/runner/work/portable-atomic/portable-atomic/target/fat-lto/x86_64-unknown-linux-gnu/release/deps/portable_atomic_util-00d6667bc63e2ad8+0xd2024) (BuildId: c0b91b02598535e2c737f09aa3b674d9ad0b0dad)

  ==9490==Register values:
  rax = 0x000001fe76937240  rbx = 0x00007ffd03fc2b40  rcx = 0x0000000000000000  rdx = 0x000000008fff6fff
  rdi = 0x00007f99a4e09010  rsi = 0x0000000000000000  rbp = 0x00007ffd03fc2bf0  rsp = 0x00007ffd03fc2b40
   r8 = 0x00000ff3b49b9200   r9 = 0x0000000000000000  r10 = 0xafffff00000fff01  r11 = 0x4000000000000000
  r12 = 0x00007ffd03fc2d18  r13 = 0x0000000000000001  r14 = 0x00007f99a4e09000  r15 = 0x00000ff3349c1200
  AddressSanitizer can not provide additional info.
  SUMMARY: AddressSanitizer: SEGV (/home/runner/work/portable-atomic/portable-atomic/target/fat-lto/x86_64-unknown-linux-gnu/release/deps/portable_atomic_util-00d6667bc63e2ad8+0x186fd7) (BuildId: c0b91b02598535e2c737f09aa3b674d9ad0b0dad)
  ==9490==ABORTING
  error: test failed, to rerun pass `--lib`

  Caused by:
    process didn't exit successfully: `/home/runner/work/portable-atomic/portable-atomic/target/fat-lto/x86_64-unknown-linux-gnu/release/deps/portable_atomic_util-00d6667bc63e2ad8` (exit status: 1)
  note: test exited abnormally; to see the full output pass --nocapture to the harness.
```

```
  MemorySanitizer init done
  MemorySanitizer:DEADLYSIGNAL
  ==9452==ERROR: MemorySanitizer: SEGV on unknown address (pc 0x562905b48101 bp 0x7ffd838eae60 sp 0x7ffd838ead70 T9452)
  ==9452==The signal is caused by a READ memory access.
  ==9452==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
      #0 0x562905b48101  (/home/runner/work/portable-atomic/portable-atomic/target/fat-lto/x86_64-unknown-linux-gnu/release/deps/portable_atomic_util-138683c7dc2360db+0x173f101) (BuildId: f6c38e887ad56074ba9df2f99079142d74ce3c51)
      #1 0x562905b47f48  (/home/runner/work/portable-atomic/portable-atomic/target/fat-lto/x86_64-unknown-linux-gnu/release/deps/portable_atomic_util-138683c7dc2360db+0x173ef48) (BuildId: f6c38e887ad56074ba9df2f99079142d74ce3c51)
      #2 0x7f5ffae2a303  (/lib/x86_64-linux-gnu/libc.so.6+0x2a303) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
      #3 0x56290458bab4  (/home/runner/work/portable-atomic/portable-atomic/target/fat-lto/x86_64-unknown-linux-gnu/release/deps/portable_atomic_util-138683c7dc2360db+0x182ab4) (BuildId: f6c38e887ad56074ba9df2f99079142d74ce3c51)

  ==9452==Register values:
  rax = 0x0000000000000000  rbx = 0x00007ffd838eae88  rcx = 0x00008ffd838eadf4  rdx = 0x00007ffd838ead00
  rdi = 0x00007ffd838eadf6  rsi = 0x0000100000000000  rbp = 0x00007ffd838eae60  rsp = 0x00007ffd838ead70
   r8 = 0x0000562905b4800c   r9 = 0x0000562908947930  r10 = 0x000056290443459f  r11 = 0x0000000000000202
  r12 = 0x0000000000000001  r13 = 0x0000000000000000  r14 = 0x000056290692dee8  r15 = 0x00007f5ffb2c6000
  MemorySanitizer can not provide additional info.
  SUMMARY: MemorySanitizer: SEGV (/home/runner/work/portable-atomic/portable-atomic/target/fat-lto/x86_64-unknown-linux-gnu/release/deps/portable_atomic_util-138683c7dc2360db+0x173f101) (BuildId: f6c38e887ad56074ba9df2f99079142d74ce3c51)
  ==9452==ABORTING
  error: test failed, to rerun pass `--lib`

  Caused by:
    process didn't exit successfully: `/home/runner/work/portable-atomic/portable-atomic/target/fat-lto/x86_64-unknown-linux-gnu/release/deps/portable_atomic_util-138683c7dc2360db` (exit status: 1)
  note: test exited abnormally; to see the full output pass --nocapture to the harness.
```