tests: Pin gba test to nightly-2024-06-21
These targets have been broken since nightly-2024-06-22.

```
test test_atomic_isize ...
panicked at src/main.rs:96:5:
assertion `left == right` failed
  left: 655370
 right: 10
Error: Tests failed!
```