Temporarily disable AVR build on latest nightly
LLVM 16 broke AVR.

```
LLVM ERROR: Expected a constant shift amount!
error: could not compile `compiler_builtins` (lib)
```