ci: Temporarily disable l4re test
```
Can't load
'/tmp/par-72756e6e6572/cache-06fd802c0261f310e480b6b5cc659a94ef3b70a2/inc/lib/auto/POSIX/POSIX.so'
for module POSIX: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.42'
not found (required by
/tmp/par-72756e6e6572/cache-06fd802c0261f310e480b6b5cc659a94ef3b70a2/inc/lib/auto/POSIX/POSIX.so)
at <embedded>/DynaLoader.pm line 201.
at <embedded>/PAR/Heavy.pm line 104.
Compilation failed in require at script/l4image line 12.
BEGIN failed--compilation aborted at script/l4image line 12.
no-std.sh:325: `l4image -i l4re_hello-2_arm_virt.elf --outputdir
workdir-arm extract` exit with 2
```