codegen: Pin globset to 0.4.9
```
error: failed to select a version for the requirement `bstr = "^1.1.0"`
candidate versions found which didn't match: 0.2.17, 0.2.16, 0.2.15, ...
location searched: crates.io index
required by package `globset v0.4.10`
    ... which satisfies dependency `globset = "^0.4"` (locked to 0.4.10) of package `portable-atomic-internal-codegen v0.0.0
```