ci: Work around cargo-careful install failure on old nightly
```
error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-careful-0.4.6/Cargo.toml`

Caused by:
  feature `edition2021` is required

  The package requires the Cargo feature called `edition2021`, but that feature is not stabilized in this version of Cargo (1.56.0-nightly (e96bdb0c3 2021-08-17)).
  Consider trying a more recent nightly release.
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2021 for more information about the status of this feature.
ERROR Cargo errored! ExitStatus(unix_wait_status(25856))
ERROR Fatal error:
  × For crate cargo-careful: subprocess cargo install cargo-careful --version
  │ 0.4.6 --force --locked errored with exit status: 101
  ╰─▶ subprocess cargo install cargo-careful --version 0.4.6 --force --locked
      errored with exit status: 101
```