ci: Mark ESP-IDF as no-std to work around upstream bug since nightly-2023-10-14
```
  error[E0583]: file not found for module `wait_status`
    --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/process/process_unsupported.rs:58:1
     |
  58 | mod wait_status;
     | ^^^^^^^^^^^^^^^^
     |
     = help: to create the module `wait_status`, create file "/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/process/wait_status.rs" or "/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/process/wait_status/mod.rs"
```