ci: Temporarily pin powerpc linux test to nightly-2025-02-17
Same error as 75a36c33b38c4c68f4095e95f106cfbedce9a914, but now also happens on nightly-2025-02-25.

```
  qemu: uncaught target signal 4 (Illegal instruction) - core dumped
  error: test failed, to rerun pass `--test arc`

  Caused by:
    process didn't exit successfully: `qemu-ppc /home/runner/work/portable-atomic/portable-atomic/target/careful/powerpc-unknown-linux-gnu/debug/deps/arc-a6e8806af1ef501f` (signal: 4, SIGILL: illegal instruction)
  test alloc_tests::manually_share_arc ... ::endgroup::
  error: process didn't exit successfully: `/home/runner/.rustup/toolchains/nightly-2025-02-25-x86_64-unknown-linux-gnu/bin/cargo careful test -Z doctest-xcompile -v --target powerpc-unknown-linux-gnu --manifest-path portable-atomic-util/Cargo.toml --features std` (exit status: 101)
```