tests: Use nightly-2023-05-25 for gba test
These targets have been broken since nightly-2023-05-26.

```
  = note: rust-lld: error: duplicate symbol: __aeabi_idiv
          >>> defined at asm_runtime.rs:248 (src/asm_runtime.rs:248)
          >>>            gba-677c4959b5cc1026.gba.1dec4fdca9d346a7-cgu.13.rcgu.o:(__aeabi_idiv) in archive /home/runner/work/portable-atomic/portable-atomic/target/armv4t-none-eabi/debug/deps/libgba-677c4959b5cc1026.rlib
          >>> defined at macros.rs:372 (src/macros.rs:372)
          >>>            compiler_builtins-76eeecd9c2640bfd.compiler_builtins.c8e3dabd92fef9ea-cgu.8.rcgu.o:(.text.__aeabi_idiv+0x0) in archive /home/runner/work/portable-atomic/portable-atomic/target/armv4t-none-eabi/debug/deps/libcompiler_builtins-76eeecd9c2640bfd.rlib

          rust-lld: error: duplicate symbol: __aeabi_uidiv
          >>> defined at asm_runtime.rs:206 (src/asm_runtime.rs:206)
          >>>            gba-677c4959b5cc1026.gba.1dec4fdca9d346a7-cgu.13.rcgu.o:(__aeabi_uidiv) in archive /home/runner/work/portable-atomic/portable-atomic/target/armv4t-none-eabi/debug/deps/libgba-677c4959b5cc1026.rlib
          >>> defined at macros.rs:372 (src/macros.rs:372)
          >>>            compiler_builtins-76eeecd9c2640bfd.compiler_builtins.c8e3dabd92fef9ea-cgu.8.rcgu.o:(.text.__aeabi_uidiv+0x0) in archive /home/runner/work/portable-atomic/portable-atomic/target/armv4t-none-eabi/debug/deps/libcompiler_builtins-76eeecd9c2640bfd.rlib
```