ci: Temporarily pin arm android test to nightly-2024-08-30
```
  panicked at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/../../backtrace/src/symbolize/gimli/libs_dl_iterate_phdr.rs:48:30:

  thread panicked while processing panic. aborting.
  libc: Fatal signal 6 (SIGABRT), code -6 in tid 22188 (alloc_tests::te)
  libc: Unable to open connection to debuggerd: Connection refused
  qemu: uncaught target signal 6 (Aborted) - core dumped
  error: test failed, to rerun pass `--test arc`

  Caused by:
    process didn't exit successfully: `qemu-arm /home/runner/work/portable-atomic/portable-atomic/target/careful/arm-linux-androideabi/debug/deps/arc-6e5994f331e3eb22` (signal: 6, SIGABRT: process abort signal)
  test alloc_tests::test_clone_from_slice_panic - should panic ... ::endgroup::
  error: process didn't exit successfully: `/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo careful test -Z doctest-xcompile -v --target arm-linux-androideabi --manifest-path portable-atomic-util/Cargo.toml --features std` (exit status: 101)
```